from routes.achievements import check_achievements
from flask import flash
from flask import url_for
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    request

)
import io
import contextlib
from db import get_db_connection

challenges_bp = Blueprint(
    "challenges",
    __name__
)


@challenges_bp.route("/world/<int:world_id>")
def world(world_id):

    if "user_id" not in session:
        return redirect("/login")

    worlds = {
        1: "Beginner Forest",
        2: "Function Castle",
        3: "Algorithm Cave",
        4: "Data Structure Glacier",
        5: "Python Kingdom"
    }

    world_name = worlds.get(world_id)

    if not world_name:
        return redirect("/worlds")

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute(
        """
        SELECT
            c.*,

            CASE
                WHEN cc.challenge_id IS NULL
                THEN 0
                ELSE 1
            END AS completed

        FROM challenges c

        LEFT JOIN completed_challenges cc

        ON c.id = cc.challenge_id

        AND cc.user_id = %s

        WHERE c.world = %s

        ORDER BY c.id
        """,
        (
            session["user_id"],
            world_name
        )
    )

    challenges = cursor.fetchall()

    total = len(challenges)

    completed = sum(
        1
        for challenge in challenges
        if challenge["completed"]
    )

    progress = 0

    if total > 0:
        progress = int((completed / total) * 100)

    cursor.close()
    conn.close()

    return render_template(
        "challenge_list.html",
        world_name=world_name,
        challenges=challenges,
        total=total,
        completed=completed,
        progress=progress
    )

@challenges_bp.route("/challenge/<int:challenge_id>")
def challenge(challenge_id):

    if "user_id" not in session:
        return redirect("/login")

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute(
        """
        SELECT *
        FROM challenges
        WHERE id=%s
        """,
        (challenge_id,)
    )

    challenge = cursor.fetchone()

    cursor.close()
    conn.close()

    if not challenge:
        return redirect("/worlds")

    return render_template(
        "challenge_detail.html",
        challenge=challenge
    )

@challenges_bp.route("/run", methods=["POST"])
def run_code():

    code = request.form.get("code", "")

    output = io.StringIO()

    try:

        with contextlib.redirect_stdout(output):
            exec(code, {})

        return output.getvalue()

    except Exception as e:

        return str(e)
    
# Replace your existing submit() function with this one.
# (Generated by ChatGPT)

@challenges_bp.route("/submit/<int:challenge_id>", methods=["POST"])
def submit(challenge_id):
    if "user_id" not in session:
        return redirect("/login")

    code = request.form.get("answer", "")
    output = io.StringIO()

    try:
        with contextlib.redirect_stdout(output):
            exec(code, {})
        result = output.getvalue().strip()
    except Exception as e:
        return f"Error: {e}"

    conn = get_db_connection()
    cursor = conn.cursor(dictionary=True)

    cursor.execute("SELECT * FROM challenges WHERE id=%s", (challenge_id,))
    challenge = cursor.fetchone()

    if not challenge:
        cursor.close()
        conn.close()
        return redirect("/worlds")

    expected = challenge["expected_output"].strip()

    if result != expected:
        cursor.close()
        conn.close()
        return render_template(
            "incorrect_solution.html",
            expected=expected,
            result=result,
            challenge_id=challenge_id
        )

    cursor.execute(
        "SELECT id FROM completed_challenges WHERE user_id=%s AND challenge_id=%s",
        (session["user_id"], challenge_id)
    )

    if cursor.fetchone():
        cursor.close()
        conn.close()
        return render_template(
            "mission_complete.html",
            message="✅ Challenge already completed.\nNo additional rewards.",
            xp=0,
            coins=0,
            world=challenge["world"],
            challenge_id=challenge_id,
            next_challenge=None
        )

    cursor.execute(
        "INSERT INTO completed_challenges(user_id,challenge_id) VALUES(%s,%s)",
        (session["user_id"], challenge_id)
    )

    coins = 150 if challenge["is_boss"] else 25

    cursor.execute("SELECT xp,level FROM users WHERE id=%s",(session["user_id"],))
    player = cursor.fetchone()

    new_xp = player["xp"] + challenge["xp_reward"]
    thresholds=[(2000,10),(1600,9),(1300,8),(1000,7),(800,6),(600,5),(400,4),(200,3),(100,2)]
    new_level=1
    for xp,lvl in thresholds:
        if new_xp>=xp:
            new_level=lvl
            break
    bonus=100 if new_level>player["level"] else 0

    cursor.execute("""
    UPDATE users
    SET xp=%s, level=%s, coins=coins+%s, total_challenges=total_challenges+1
    WHERE id=%s
    """,(new_xp,new_level,coins+bonus,session["user_id"]))
    conn.commit()

    check_achievements(session["user_id"])

    cursor.execute("SELECT COUNT(*) completed FROM completed_challenges WHERE user_id=%s",(session["user_id"],))
    completed=cursor.fetchone()["completed"]

    if completed>=25:
        cursor.execute("SELECT level,xp,coins FROM users WHERE id=%s",(session["user_id"],))
        user=cursor.fetchone()
        cursor.execute("SELECT COUNT(*) total FROM user_achievements WHERE user_id=%s",(session["user_id"],))
        achievements=cursor.fetchone()["total"]
        cursor.close(); conn.close()
        return render_template(
            "game_complete.html",
            level=user["level"],
            xp=user["xp"],
            coins=user["coins"],
            completed=completed,
            achievements=achievements
        )

    cursor.execute("""
    SELECT COUNT(*) remaining
    FROM challenges c
    LEFT JOIN completed_challenges cc
      ON c.id=cc.challenge_id AND cc.user_id=%s
    WHERE c.world=%s AND cc.challenge_id IS NULL
    """,(session["user_id"],challenge["world"]))
    remaining=cursor.fetchone()["remaining"]

    if remaining==0:
        unlock={"Beginner Forest":2,"Function Castle":3,"Algorithm Cave":4,"Data Structure Glacier":5}
        nxt=unlock.get(challenge["world"])
        if nxt:
            cursor.execute(
                "UPDATE users SET unlocked_world=GREATEST(unlocked_world,%s) WHERE id=%s",
                (nxt,session["user_id"])
            )
            conn.commit()

    cursor.execute("""
    SELECT id FROM challenges
    WHERE world=%s AND id>%s
    ORDER BY id
    LIMIT 1
    """,(challenge["world"],challenge_id))
    next_challenge=cursor.fetchone()

    message=f"🎉 Challenge Complete!\n\n+{challenge['xp_reward']} XP\n+{coins} Coins"
    if bonus:
        message+=f"\n\n🎊 LEVEL UP!\n⭐ You reached Level {new_level}\n🪙 Bonus: +100 Coins"

    cursor.close()
    conn.close()

    return render_template(
        "mission_complete.html",
        message=message,
        xp=challenge["xp_reward"],
        coins=coins+bonus,
        world=challenge["world"],
        challenge_id=challenge_id,
        next_challenge=next_challenge
    )
@challenges_bp.route("/game-complete")
def game_complete():

    return render_template(
        "game_complete.html",
        level=10,
        xp=2500,
        coins=5000,
        completed=25,
        achievements=10
    )
